language: java
script: gradle fatJar
services:
- docker
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - DOCKER_USER=alimohammadi340
  - secure: PIC9BVbzxq1mOBi7p3Gkig58bSlorgbD+5LpQsBwz3X9kwcpJp3hh1RskHJxyBDizaGKvJIbP91ox00GoldVXc1vCbbWJKEwPjJhp/WgcKM/tCu3G0h5naIysLFSkD96vAURYlF55pFfGJvGJjmHWThfUsEeBsFEDRQYPqEiKfYq/e9jPu3pcAt5li0V8dNV4mHJlFtm2ONzUYoZPMXGeKDZf6I0v2qiRnUZAKrVV/0n728fKP3fTBQ/Tlx0W3Mx3fnNFeR9PsWpfoEkrkkkhxHL48vas7iJBGOXQWNrvrThMEToLkYb7agu5fXfEHt/Dsp82NmJ0NHp1PEMUZ3uEuzEmRXZELJu/Rkqx0bbRAo0vNyYowCh5zO3Y1u7cmvj8RlJ0Z5FvbPqAfOnPDaxg9PufFlaTPjZIlXkzzkg7WohRhCKjKfO31QQfS5hZUIymZBbxhtK0/SezRgSfmfe/J/RdGpeZ+W11VahK8eiAscMbz5aNS4yS+EcdpYKvushMzMtSVyVrz7CkWpB/KRgnlFGvXpXsugpzOjRZx+hAiAs3pQfkeDhU0MDAZ7IDeMrz7N9bBy4IPdhZVz1yzdyf4IpyU43ypBa0Wvi2zuzTTXbElXugV8sZnRyvjqMK8mUc4Ad34YCy80ZinkMRg5P3CHXqvuJQlOCu8HkERY6QkQ=
  - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - docker login quay.io -e alimohammadi340@gmail.com -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=quay.io/alimohammadi340/hoomcode-server
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker image ls
  - docker push $REPO